//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ExpenseReportModel", "FK_tblEmployees_tblDepartment", "tblDepartment", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExpenseReports.Models.tblDepartment), "tblEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpenseReports.Models.tblEmployee), true)]
[assembly: EdmRelationshipAttribute("ExpenseReportModel", "FK_tblExpenseReports_tblEmployees", "tblEmployees", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExpenseReports.Models.tblEmployee), "tblExpenseReports", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpenseReports.Models.tblExpenseReport), true)]
[assembly: EdmRelationshipAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseCategories", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExpenseReports.Models.tblExpenseCategory), "tblExpenseDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpenseReports.Models.tblExpenseDetail), true)]
[assembly: EdmRelationshipAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblExpenseReports", "tblExpenseReports", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ExpenseReports.Models.tblExpenseReport), "tblExpenseDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpenseReports.Models.tblExpenseDetail), true)]
[assembly: EdmRelationshipAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblProvinceRates", "tblProvinceRates", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(ExpenseReports.Models.tblProvinceRate), "tblExpenseDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ExpenseReports.Models.tblExpenseDetail), true)]

#endregion

namespace ExpenseReports.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ExpenseReportEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ExpenseReportEntities object using the connection string found in the 'ExpenseReportEntities' section of the application configuration file.
        /// </summary>
        public ExpenseReportEntities() : base("name=ExpenseReportEntities", "ExpenseReportEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpenseReportEntities object.
        /// </summary>
        public ExpenseReportEntities(string connectionString) : base(connectionString, "ExpenseReportEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ExpenseReportEntities object.
        /// </summary>
        public ExpenseReportEntities(EntityConnection connection) : base(connection, "ExpenseReportEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblDepartment> tblDepartments
        {
            get
            {
                if ((_tblDepartments == null))
                {
                    _tblDepartments = base.CreateObjectSet<tblDepartment>("tblDepartments");
                }
                return _tblDepartments;
            }
        }
        private ObjectSet<tblDepartment> _tblDepartments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblEmployee> tblEmployees
        {
            get
            {
                if ((_tblEmployees == null))
                {
                    _tblEmployees = base.CreateObjectSet<tblEmployee>("tblEmployees");
                }
                return _tblEmployees;
            }
        }
        private ObjectSet<tblEmployee> _tblEmployees;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblExpenseCategory> tblExpenseCategories
        {
            get
            {
                if ((_tblExpenseCategories == null))
                {
                    _tblExpenseCategories = base.CreateObjectSet<tblExpenseCategory>("tblExpenseCategories");
                }
                return _tblExpenseCategories;
            }
        }
        private ObjectSet<tblExpenseCategory> _tblExpenseCategories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblExpenseDetail> tblExpenseDetails
        {
            get
            {
                if ((_tblExpenseDetails == null))
                {
                    _tblExpenseDetails = base.CreateObjectSet<tblExpenseDetail>("tblExpenseDetails");
                }
                return _tblExpenseDetails;
            }
        }
        private ObjectSet<tblExpenseDetail> _tblExpenseDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblExpenseReport> tblExpenseReports
        {
            get
            {
                if ((_tblExpenseReports == null))
                {
                    _tblExpenseReports = base.CreateObjectSet<tblExpenseReport>("tblExpenseReports");
                }
                return _tblExpenseReports;
            }
        }
        private ObjectSet<tblExpenseReport> _tblExpenseReports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblGuest> tblGuests
        {
            get
            {
                if ((_tblGuests == null))
                {
                    _tblGuests = base.CreateObjectSet<tblGuest>("tblGuests");
                }
                return _tblGuests;
            }
        }
        private ObjectSet<tblGuest> _tblGuests;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblProvinceRate> tblProvinceRates
        {
            get
            {
                if ((_tblProvinceRates == null))
                {
                    _tblProvinceRates = base.CreateObjectSet<tblProvinceRate>("tblProvinceRates");
                }
                return _tblProvinceRates;
            }
        }
        private ObjectSet<tblProvinceRate> _tblProvinceRates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblTax> tblTaxes
        {
            get
            {
                if ((_tblTaxes == null))
                {
                    _tblTaxes = base.CreateObjectSet<tblTax>("tblTaxes");
                }
                return _tblTaxes;
            }
        }
        private ObjectSet<tblTax> _tblTaxes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblDepartments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblDepartments(tblDepartment tblDepartment)
        {
            base.AddObject("tblDepartments", tblDepartment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblEmployees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblEmployees(tblEmployee tblEmployee)
        {
            base.AddObject("tblEmployees", tblEmployee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblExpenseCategories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblExpenseCategories(tblExpenseCategory tblExpenseCategory)
        {
            base.AddObject("tblExpenseCategories", tblExpenseCategory);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblExpenseDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblExpenseDetails(tblExpenseDetail tblExpenseDetail)
        {
            base.AddObject("tblExpenseDetails", tblExpenseDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblExpenseReports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblExpenseReports(tblExpenseReport tblExpenseReport)
        {
            base.AddObject("tblExpenseReports", tblExpenseReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblGuests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblGuests(tblGuest tblGuest)
        {
            base.AddObject("tblGuests", tblGuest);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblProvinceRates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblProvinceRates(tblProvinceRate tblProvinceRate)
        {
            base.AddObject("tblProvinceRates", tblProvinceRate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblTaxes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblTaxes(tblTax tblTax)
        {
            base.AddObject("tblTaxes", tblTax);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblDepartment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblDepartment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblDepartment object.
        /// </summary>
        /// <param name="departmentID">Initial value of the DepartmentID property.</param>
        public static tblDepartment CreatetblDepartment(global::System.Int32 departmentID)
        {
            tblDepartment tblDepartment = new tblDepartment();
            tblDepartment.DepartmentID = departmentID;
            return tblDepartment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                if (_DepartmentID != value)
                {
                    OnDepartmentIDChanging(value);
                    ReportPropertyChanging("DepartmentID");
                    _DepartmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentID");
                    OnDepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentNumber
        {
            get
            {
                return _DepartmentNumber;
            }
            set
            {
                OnDepartmentNumberChanging(value);
                ReportPropertyChanging("DepartmentNumber");
                _DepartmentNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentNumber");
                OnDepartmentNumberChanged();
            }
        }
        private global::System.String _DepartmentNumber;
        partial void OnDepartmentNumberChanging(global::System.String value);
        partial void OnDepartmentNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblEmployees_tblDepartment", "tblEmployees")]
        public EntityCollection<tblEmployee> tblEmployees
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblEmployee>("ExpenseReportModel.FK_tblEmployees_tblDepartment", "tblEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblEmployee>("ExpenseReportModel.FK_tblEmployees_tblDepartment", "tblEmployees", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblEmployee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblEmployee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblEmployee object.
        /// </summary>
        /// <param name="employeeID">Initial value of the EmployeeID property.</param>
        /// <param name="carAllowance">Initial value of the CarAllowance property.</param>
        public static tblEmployee CreatetblEmployee(global::System.Int32 employeeID, global::System.Boolean carAllowance)
        {
            tblEmployee tblEmployee = new tblEmployee();
            tblEmployee.EmployeeID = employeeID;
            tblEmployee.CarAllowance = carAllowance;
            return tblEmployee;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                if (_EmployeeID != value)
                {
                    OnEmployeeIDChanging(value);
                    ReportPropertyChanging("EmployeeID");
                    _EmployeeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmployeeID");
                    OnEmployeeIDChanged();
                }
            }
        }
        private global::System.Int32 _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.Int32 value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                OnDepartmentIDChanging(value);
                ReportPropertyChanging("DepartmentID");
                _DepartmentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentID");
                OnDepartmentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DepartmentID;
        partial void OnDepartmentIDChanging(Nullable<global::System.Int32> value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailName
        {
            get
            {
                return _EmailName;
            }
            set
            {
                OnEmailNameChanging(value);
                ReportPropertyChanging("EmailName");
                _EmailName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailName");
                OnEmailNameChanged();
            }
        }
        private global::System.String _EmailName;
        partial void OnEmailNameChanging(global::System.String value);
        partial void OnEmailNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Extension
        {
            get
            {
                return _Extension;
            }
            set
            {
                OnExtensionChanging(value);
                ReportPropertyChanging("Extension");
                _Extension = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Extension");
                OnExtensionChanged();
            }
        }
        private global::System.String _Extension;
        partial void OnExtensionChanging(global::System.String value);
        partial void OnExtensionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProvinceID
        {
            get
            {
                return _ProvinceID;
            }
            set
            {
                OnProvinceIDChanging(value);
                ReportPropertyChanging("ProvinceID");
                _ProvinceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProvinceID");
                OnProvinceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ProvinceID;
        partial void OnProvinceIDChanging(Nullable<global::System.Int32> value);
        partial void OnProvinceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CarAllowance
        {
            get
            {
                return _CarAllowance;
            }
            set
            {
                OnCarAllowanceChanging(value);
                ReportPropertyChanging("CarAllowance");
                _CarAllowance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CarAllowance");
                OnCarAllowanceChanged();
            }
        }
        private global::System.Boolean _CarAllowance;
        partial void OnCarAllowanceChanging(global::System.Boolean value);
        partial void OnCarAllowanceChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblEmployees_tblDepartment", "tblDepartment")]
        public tblDepartment tblDepartment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDepartment>("ExpenseReportModel.FK_tblEmployees_tblDepartment", "tblDepartment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDepartment>("ExpenseReportModel.FK_tblEmployees_tblDepartment", "tblDepartment").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblDepartment> tblDepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblDepartment>("ExpenseReportModel.FK_tblEmployees_tblDepartment", "tblDepartment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblDepartment>("ExpenseReportModel.FK_tblEmployees_tblDepartment", "tblDepartment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseReports_tblEmployees", "tblExpenseReports")]
        public EntityCollection<tblExpenseReport> tblExpenseReports
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblExpenseReport>("ExpenseReportModel.FK_tblExpenseReports_tblEmployees", "tblExpenseReports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblExpenseReport>("ExpenseReportModel.FK_tblExpenseReports_tblEmployees", "tblExpenseReports", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblExpenseCategory")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblExpenseCategory : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblExpenseCategory object.
        /// </summary>
        /// <param name="categoryID">Initial value of the CategoryID property.</param>
        public static tblExpenseCategory CreatetblExpenseCategory(global::System.Int32 categoryID)
        {
            tblExpenseCategory tblExpenseCategory = new tblExpenseCategory();
            tblExpenseCategory.CategoryID = categoryID;
            return tblExpenseCategory;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                if (_CategoryID != value)
                {
                    OnCategoryIDChanging(value);
                    ReportPropertyChanging("CategoryID");
                    _CategoryID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CategoryID");
                    OnCategoryIDChanged();
                }
            }
        }
        private global::System.Int32 _CategoryID;
        partial void OnCategoryIDChanging(global::System.Int32 value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Exemples
        {
            get
            {
                return _Exemples;
            }
            set
            {
                OnExemplesChanging(value);
                ReportPropertyChanging("Exemples");
                _Exemples = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Exemples");
                OnExemplesChanged();
            }
        }
        private global::System.String _Exemples;
        partial void OnExemplesChanging(global::System.String value);
        partial void OnExemplesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GL_Account
        {
            get
            {
                return _GL_Account;
            }
            set
            {
                OnGL_AccountChanging(value);
                ReportPropertyChanging("GL_Account");
                _GL_Account = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GL_Account");
                OnGL_AccountChanged();
            }
        }
        private global::System.String _GL_Account;
        partial void OnGL_AccountChanging(global::System.String value);
        partial void OnGL_AccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GST
        {
            get
            {
                return _GST;
            }
            set
            {
                OnGSTChanging(value);
                ReportPropertyChanging("GST");
                _GST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GST");
                OnGSTChanged();
            }
        }
        private Nullable<global::System.Double> _GST;
        partial void OnGSTChanging(Nullable<global::System.Double> value);
        partial void OnGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PST
        {
            get
            {
                return _PST;
            }
            set
            {
                OnPSTChanging(value);
                ReportPropertyChanging("PST");
                _PST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PST");
                OnPSTChanged();
            }
        }
        private Nullable<global::System.Double> _PST;
        partial void OnPSTChanging(Nullable<global::System.Double> value);
        partial void OnPSTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseDetails")]
        public EntityCollection<tblExpenseDetail> tblExpenseDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblExpenseDetail>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblExpenseDetail>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblExpenseDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblExpenseDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblExpenseDetail object.
        /// </summary>
        /// <param name="expenseDetailID">Initial value of the ExpenseDetailID property.</param>
        /// <param name="expenseReportID">Initial value of the ExpenseReportID property.</param>
        public static tblExpenseDetail CreatetblExpenseDetail(global::System.Int32 expenseDetailID, global::System.Int32 expenseReportID)
        {
            tblExpenseDetail tblExpenseDetail = new tblExpenseDetail();
            tblExpenseDetail.ExpenseDetailID = expenseDetailID;
            tblExpenseDetail.ExpenseReportID = expenseReportID;
            return tblExpenseDetail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExpenseDetailID
        {
            get
            {
                return _ExpenseDetailID;
            }
            set
            {
                if (_ExpenseDetailID != value)
                {
                    OnExpenseDetailIDChanging(value);
                    ReportPropertyChanging("ExpenseDetailID");
                    _ExpenseDetailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExpenseDetailID");
                    OnExpenseDetailIDChanged();
                }
            }
        }
        private global::System.Int32 _ExpenseDetailID;
        partial void OnExpenseDetailIDChanging(global::System.Int32 value);
        partial void OnExpenseDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExpenseReportID
        {
            get
            {
                return _ExpenseReportID;
            }
            set
            {
                OnExpenseReportIDChanging(value);
                ReportPropertyChanging("ExpenseReportID");
                _ExpenseReportID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpenseReportID");
                OnExpenseReportIDChanged();
            }
        }
        private global::System.Int32 _ExpenseReportID;
        partial void OnExpenseReportIDChanging(global::System.Int32 value);
        partial void OnExpenseReportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CategoryID
        {
            get
            {
                return _CategoryID;
            }
            set
            {
                OnCategoryIDChanging(value);
                ReportPropertyChanging("CategoryID");
                _CategoryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryID");
                OnCategoryIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CategoryID;
        partial void OnCategoryIDChanging(Nullable<global::System.Int32> value);
        partial void OnCategoryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ExpenseItemAmount
        {
            get
            {
                return _ExpenseItemAmount;
            }
            set
            {
                OnExpenseItemAmountChanging(value);
                ReportPropertyChanging("ExpenseItemAmount");
                _ExpenseItemAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpenseItemAmount");
                OnExpenseItemAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _ExpenseItemAmount;
        partial void OnExpenseItemAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnExpenseItemAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpenseItemDescription
        {
            get
            {
                return _ExpenseItemDescription;
            }
            set
            {
                OnExpenseItemDescriptionChanging(value);
                ReportPropertyChanging("ExpenseItemDescription");
                _ExpenseItemDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpenseItemDescription");
                OnExpenseItemDescriptionChanged();
            }
        }
        private global::System.String _ExpenseItemDescription;
        partial void OnExpenseItemDescriptionChanging(global::System.String value);
        partial void OnExpenseItemDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpenseDate
        {
            get
            {
                return _ExpenseDate;
            }
            set
            {
                OnExpenseDateChanging(value);
                ReportPropertyChanging("ExpenseDate");
                _ExpenseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpenseDate");
                OnExpenseDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpenseDate;
        partial void OnExpenseDateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpenseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Tip
        {
            get
            {
                return _Tip;
            }
            set
            {
                OnTipChanging(value);
                ReportPropertyChanging("Tip");
                _Tip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tip");
                OnTipChanged();
            }
        }
        private Nullable<global::System.Decimal> _Tip;
        partial void OnTipChanging(Nullable<global::System.Decimal> value);
        partial void OnTipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Lodging_Taxes
        {
            get
            {
                return _Lodging_Taxes;
            }
            set
            {
                OnLodging_TaxesChanging(value);
                ReportPropertyChanging("Lodging_Taxes");
                _Lodging_Taxes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lodging_Taxes");
                OnLodging_TaxesChanged();
            }
        }
        private Nullable<global::System.Decimal> _Lodging_Taxes;
        partial void OnLodging_TaxesChanging(Nullable<global::System.Decimal> value);
        partial void OnLodging_TaxesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Non_TaxableExtras
        {
            get
            {
                return _Non_TaxableExtras;
            }
            set
            {
                OnNon_TaxableExtrasChanging(value);
                ReportPropertyChanging("Non_TaxableExtras");
                _Non_TaxableExtras = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Non_TaxableExtras");
                OnNon_TaxableExtrasChanged();
            }
        }
        private Nullable<global::System.Decimal> _Non_TaxableExtras;
        partial void OnNon_TaxableExtrasChanging(Nullable<global::System.Decimal> value);
        partial void OnNon_TaxableExtrasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProvinceID
        {
            get
            {
                return _ProvinceID;
            }
            set
            {
                OnProvinceIDChanging(value);
                ReportPropertyChanging("ProvinceID");
                _ProvinceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProvinceID");
                OnProvinceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ProvinceID;
        partial void OnProvinceIDChanging(Nullable<global::System.Int32> value);
        partial void OnProvinceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TaxCategory
        {
            get
            {
                return _TaxCategory;
            }
            set
            {
                OnTaxCategoryChanging(value);
                ReportPropertyChanging("TaxCategory");
                _TaxCategory = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TaxCategory");
                OnTaxCategoryChanged();
            }
        }
        private global::System.String _TaxCategory;
        partial void OnTaxCategoryChanging(global::System.String value);
        partial void OnTaxCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpenseType
        {
            get
            {
                return _ExpenseType;
            }
            set
            {
                OnExpenseTypeChanging(value);
                ReportPropertyChanging("ExpenseType");
                _ExpenseType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpenseType");
                OnExpenseTypeChanged();
            }
        }
        private global::System.String _ExpenseType;
        partial void OnExpenseTypeChanging(global::System.String value);
        partial void OnExpenseTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transaction
        {
            get
            {
                return _Transaction;
            }
            set
            {
                OnTransactionChanging(value);
                ReportPropertyChanging("Transaction");
                _Transaction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transaction");
                OnTransactionChanged();
            }
        }
        private global::System.String _Transaction;
        partial void OnTransactionChanging(global::System.String value);
        partial void OnTransactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Currency
        {
            get
            {
                return _Currency;
            }
            set
            {
                OnCurrencyChanging(value);
                ReportPropertyChanging("Currency");
                _Currency = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Currency");
                OnCurrencyChanged();
            }
        }
        private global::System.String _Currency;
        partial void OnCurrencyChanging(global::System.String value);
        partial void OnCurrencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> AGST
        {
            get
            {
                return _AGST;
            }
            set
            {
                OnAGSTChanging(value);
                ReportPropertyChanging("AGST");
                _AGST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AGST");
                OnAGSTChanged();
            }
        }
        private Nullable<global::System.Double> _AGST;
        partial void OnAGSTChanging(Nullable<global::System.Double> value);
        partial void OnAGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> AQST
        {
            get
            {
                return _AQST;
            }
            set
            {
                OnAQSTChanging(value);
                ReportPropertyChanging("AQST");
                _AQST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AQST");
                OnAQSTChanged();
            }
        }
        private Nullable<global::System.Double> _AQST;
        partial void OnAQSTChanging(Nullable<global::System.Double> value);
        partial void OnAQSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Km
        {
            get
            {
                return _Km;
            }
            set
            {
                OnKmChanging(value);
                ReportPropertyChanging("Km");
                _Km = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Km");
                OnKmChanged();
            }
        }
        private Nullable<global::System.Double> _Km;
        partial void OnKmChanging(Nullable<global::System.Double> value);
        partial void OnKmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Km_Rate
        {
            get
            {
                return _Km_Rate;
            }
            set
            {
                OnKm_RateChanging(value);
                ReportPropertyChanging("Km_Rate");
                _Km_Rate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Km_Rate");
                OnKm_RateChanged();
            }
        }
        private Nullable<global::System.Double> _Km_Rate;
        partial void OnKm_RateChanging(Nullable<global::System.Double> value);
        partial void OnKm_RateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseCategories")]
        public tblExpenseCategory tblExpenseCategory
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblExpenseCategory>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseCategories").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblExpenseCategory>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseCategories").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblExpenseCategory> tblExpenseCategoryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblExpenseCategory>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseCategories");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblExpenseCategory>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseCategories", "tblExpenseCategories", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblExpenseReports", "tblExpenseReports")]
        public tblExpenseReport tblExpenseReport
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblExpenseReport>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseReports", "tblExpenseReports").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblExpenseReport>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseReports", "tblExpenseReports").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblExpenseReport> tblExpenseReportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblExpenseReport>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseReports", "tblExpenseReports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblExpenseReport>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseReports", "tblExpenseReports", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblProvinceRates", "tblProvinceRates")]
        public tblProvinceRate tblProvinceRate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProvinceRate>("ExpenseReportModel.FK_tblExpenseDetails_tblProvinceRates", "tblProvinceRates").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProvinceRate>("ExpenseReportModel.FK_tblExpenseDetails_tblProvinceRates", "tblProvinceRates").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblProvinceRate> tblProvinceRateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblProvinceRate>("ExpenseReportModel.FK_tblExpenseDetails_tblProvinceRates", "tblProvinceRates");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblProvinceRate>("ExpenseReportModel.FK_tblExpenseDetails_tblProvinceRates", "tblProvinceRates", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblExpenseReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblExpenseReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblExpenseReport object.
        /// </summary>
        /// <param name="expenseReportID">Initial value of the ExpenseReportID property.</param>
        /// <param name="paid">Initial value of the Paid property.</param>
        public static tblExpenseReport CreatetblExpenseReport(global::System.Int32 expenseReportID, global::System.Boolean paid)
        {
            tblExpenseReport tblExpenseReport = new tblExpenseReport();
            tblExpenseReport.ExpenseReportID = expenseReportID;
            tblExpenseReport.Paid = paid;
            return tblExpenseReport;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExpenseReportID
        {
            get
            {
                return _ExpenseReportID;
            }
            set
            {
                if (_ExpenseReportID != value)
                {
                    OnExpenseReportIDChanging(value);
                    ReportPropertyChanging("ExpenseReportID");
                    _ExpenseReportID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExpenseReportID");
                    OnExpenseReportIDChanged();
                }
            }
        }
        private global::System.Int32 _ExpenseReportID;
        partial void OnExpenseReportIDChanging(global::System.Int32 value);
        partial void OnExpenseReportIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private Nullable<global::System.Int32> _EmployeeID;
        partial void OnEmployeeIDChanging(Nullable<global::System.Int32> value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpenseType
        {
            get
            {
                return _ExpenseType;
            }
            set
            {
                OnExpenseTypeChanging(value);
                ReportPropertyChanging("ExpenseType");
                _ExpenseType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpenseType");
                OnExpenseTypeChanged();
            }
        }
        private global::System.String _ExpenseType;
        partial void OnExpenseTypeChanging(global::System.String value);
        partial void OnExpenseTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpenseDate
        {
            get
            {
                return _ExpenseDate;
            }
            set
            {
                OnExpenseDateChanging(value);
                ReportPropertyChanging("ExpenseDate");
                _ExpenseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpenseDate");
                OnExpenseDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpenseDate;
        partial void OnExpenseDateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpenseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpenseRptName
        {
            get
            {
                return _ExpenseRptName;
            }
            set
            {
                OnExpenseRptNameChanging(value);
                ReportPropertyChanging("ExpenseRptName");
                _ExpenseRptName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpenseRptName");
                OnExpenseRptNameChanged();
            }
        }
        private global::System.String _ExpenseRptName;
        partial void OnExpenseRptNameChanging(global::System.String value);
        partial void OnExpenseRptNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExpenseRptDescr
        {
            get
            {
                return _ExpenseRptDescr;
            }
            set
            {
                OnExpenseRptDescrChanging(value);
                ReportPropertyChanging("ExpenseRptDescr");
                _ExpenseRptDescr = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExpenseRptDescr");
                OnExpenseRptDescrChanged();
            }
        }
        private global::System.String _ExpenseRptDescr;
        partial void OnExpenseRptDescrChanging(global::System.String value);
        partial void OnExpenseRptDescrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateSubmitted
        {
            get
            {
                return _DateSubmitted;
            }
            set
            {
                OnDateSubmittedChanging(value);
                ReportPropertyChanging("DateSubmitted");
                _DateSubmitted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateSubmitted");
                OnDateSubmittedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateSubmitted;
        partial void OnDateSubmittedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateSubmittedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> AdvanceAmount
        {
            get
            {
                return _AdvanceAmount;
            }
            set
            {
                OnAdvanceAmountChanging(value);
                ReportPropertyChanging("AdvanceAmount");
                _AdvanceAmount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdvanceAmount");
                OnAdvanceAmountChanged();
            }
        }
        private Nullable<global::System.Decimal> _AdvanceAmount;
        partial void OnAdvanceAmountChanging(Nullable<global::System.Decimal> value);
        partial void OnAdvanceAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentCharged
        {
            get
            {
                return _DepartmentCharged;
            }
            set
            {
                OnDepartmentChargedChanging(value);
                ReportPropertyChanging("DepartmentCharged");
                _DepartmentCharged = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentCharged");
                OnDepartmentChargedChanged();
            }
        }
        private global::System.String _DepartmentCharged;
        partial void OnDepartmentChargedChanging(global::System.String value);
        partial void OnDepartmentChargedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BusinessPurpose
        {
            get
            {
                return _BusinessPurpose;
            }
            set
            {
                OnBusinessPurposeChanging(value);
                ReportPropertyChanging("BusinessPurpose");
                _BusinessPurpose = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BusinessPurpose");
                OnBusinessPurposeChanged();
            }
        }
        private global::System.String _BusinessPurpose;
        partial void OnBusinessPurposeChanging(global::System.String value);
        partial void OnBusinessPurposeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Paid
        {
            get
            {
                return _Paid;
            }
            set
            {
                OnPaidChanging(value);
                ReportPropertyChanging("Paid");
                _Paid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Paid");
                OnPaidChanged();
            }
        }
        private global::System.Boolean _Paid;
        partial void OnPaidChanging(global::System.Boolean value);
        partial void OnPaidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ExchangeRate
        {
            get
            {
                return _ExchangeRate;
            }
            set
            {
                OnExchangeRateChanging(value);
                ReportPropertyChanging("ExchangeRate");
                _ExchangeRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExchangeRate");
                OnExchangeRateChanged();
            }
        }
        private Nullable<global::System.Double> _ExchangeRate;
        partial void OnExchangeRateChanging(Nullable<global::System.Double> value);
        partial void OnExchangeRateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Payment
        {
            get
            {
                return _Payment;
            }
            set
            {
                OnPaymentChanging(value);
                ReportPropertyChanging("Payment");
                _Payment = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Payment");
                OnPaymentChanged();
            }
        }
        private Nullable<global::System.Int32> _Payment;
        partial void OnPaymentChanging(Nullable<global::System.Int32> value);
        partial void OnPaymentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseReports_tblEmployees", "tblEmployees")]
        public tblEmployee tblEmployee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblEmployee>("ExpenseReportModel.FK_tblExpenseReports_tblEmployees", "tblEmployees").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblEmployee>("ExpenseReportModel.FK_tblExpenseReports_tblEmployees", "tblEmployees").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblEmployee> tblEmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblEmployee>("ExpenseReportModel.FK_tblExpenseReports_tblEmployees", "tblEmployees");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblEmployee>("ExpenseReportModel.FK_tblExpenseReports_tblEmployees", "tblEmployees", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblExpenseReports", "tblExpenseDetails")]
        public EntityCollection<tblExpenseDetail> tblExpenseDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblExpenseDetail>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseReports", "tblExpenseDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblExpenseDetail>("ExpenseReportModel.FK_tblExpenseDetails_tblExpenseReports", "tblExpenseDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblGuest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblGuest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblGuest object.
        /// </summary>
        /// <param name="guestID">Initial value of the GuestID property.</param>
        public static tblGuest CreatetblGuest(global::System.Int32 guestID)
        {
            tblGuest tblGuest = new tblGuest();
            tblGuest.GuestID = guestID;
            return tblGuest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GuestID
        {
            get
            {
                return _GuestID;
            }
            set
            {
                if (_GuestID != value)
                {
                    OnGuestIDChanging(value);
                    ReportPropertyChanging("GuestID");
                    _GuestID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GuestID");
                    OnGuestIDChanged();
                }
            }
        }
        private global::System.Int32 _GuestID;
        partial void OnGuestIDChanging(global::System.Int32 value);
        partial void OnGuestIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ExpenseDetailID
        {
            get
            {
                return _ExpenseDetailID;
            }
            set
            {
                OnExpenseDetailIDChanging(value);
                ReportPropertyChanging("ExpenseDetailID");
                _ExpenseDetailID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpenseDetailID");
                OnExpenseDetailIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ExpenseDetailID;
        partial void OnExpenseDetailIDChanging(Nullable<global::System.Int32> value);
        partial void OnExpenseDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblProvinceRate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblProvinceRate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblProvinceRate object.
        /// </summary>
        /// <param name="provinceID">Initial value of the ProvinceID property.</param>
        public static tblProvinceRate CreatetblProvinceRate(global::System.Int32 provinceID)
        {
            tblProvinceRate tblProvinceRate = new tblProvinceRate();
            tblProvinceRate.ProvinceID = provinceID;
            return tblProvinceRate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProvinceID
        {
            get
            {
                return _ProvinceID;
            }
            set
            {
                if (_ProvinceID != value)
                {
                    OnProvinceIDChanging(value);
                    ReportPropertyChanging("ProvinceID");
                    _ProvinceID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProvinceID");
                    OnProvinceIDChanged();
                }
            }
        }
        private global::System.Int32 _ProvinceID;
        partial void OnProvinceIDChanging(global::System.Int32 value);
        partial void OnProvinceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Province
        {
            get
            {
                return _Province;
            }
            set
            {
                OnProvinceChanging(value);
                ReportPropertyChanging("Province");
                _Province = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Province");
                OnProvinceChanged();
            }
        }
        private global::System.String _Province;
        partial void OnProvinceChanging(global::System.String value);
        partial void OnProvinceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GST
        {
            get
            {
                return _GST;
            }
            set
            {
                OnGSTChanging(value);
                ReportPropertyChanging("GST");
                _GST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GST");
                OnGSTChanged();
            }
        }
        private Nullable<global::System.Double> _GST;
        partial void OnGSTChanging(Nullable<global::System.Double> value);
        partial void OnGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PST
        {
            get
            {
                return _PST;
            }
            set
            {
                OnPSTChanging(value);
                ReportPropertyChanging("PST");
                _PST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PST");
                OnPSTChanged();
            }
        }
        private Nullable<global::System.Double> _PST;
        partial void OnPSTChanging(Nullable<global::System.Double> value);
        partial void OnPSTChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ExpenseReportModel", "FK_tblExpenseDetails_tblProvinceRates", "tblExpenseDetails")]
        public EntityCollection<tblExpenseDetail> tblExpenseDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblExpenseDetail>("ExpenseReportModel.FK_tblExpenseDetails_tblProvinceRates", "tblExpenseDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblExpenseDetail>("ExpenseReportModel.FK_tblExpenseDetails_tblProvinceRates", "tblExpenseDetails", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ExpenseReportModel", Name="tblTax")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblTax : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblTax object.
        /// </summary>
        /// <param name="taxID">Initial value of the TaxID property.</param>
        public static tblTax CreatetblTax(global::System.Int32 taxID)
        {
            tblTax tblTax = new tblTax();
            tblTax.TaxID = taxID;
            return tblTax;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TaxID
        {
            get
            {
                return _TaxID;
            }
            set
            {
                if (_TaxID != value)
                {
                    OnTaxIDChanging(value);
                    ReportPropertyChanging("TaxID");
                    _TaxID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaxID");
                    OnTaxIDChanged();
                }
            }
        }
        private global::System.Int32 _TaxID;
        partial void OnTaxIDChanging(global::System.Int32 value);
        partial void OnTaxIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProvinceID
        {
            get
            {
                return _ProvinceID;
            }
            set
            {
                OnProvinceIDChanging(value);
                ReportPropertyChanging("ProvinceID");
                _ProvinceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProvinceID");
                OnProvinceIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ProvinceID;
        partial void OnProvinceIDChanging(Nullable<global::System.Int32> value);
        partial void OnProvinceIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GST
        {
            get
            {
                return _GST;
            }
            set
            {
                OnGSTChanging(value);
                ReportPropertyChanging("GST");
                _GST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GST");
                OnGSTChanged();
            }
        }
        private Nullable<global::System.Double> _GST;
        partial void OnGSTChanging(Nullable<global::System.Double> value);
        partial void OnGSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PST
        {
            get
            {
                return _PST;
            }
            set
            {
                OnPSTChanging(value);
                ReportPropertyChanging("PST");
                _PST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PST");
                OnPSTChanged();
            }
        }
        private Nullable<global::System.Double> _PST;
        partial void OnPSTChanging(Nullable<global::System.Double> value);
        partial void OnPSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateStart
        {
            get
            {
                return _DateStart;
            }
            set
            {
                OnDateStartChanging(value);
                ReportPropertyChanging("DateStart");
                _DateStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStart");
                OnDateStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateStart;
        partial void OnDateStartChanging(Nullable<global::System.DateTime> value);
        partial void OnDateStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateEnd
        {
            get
            {
                return _DateEnd;
            }
            set
            {
                OnDateEndChanging(value);
                ReportPropertyChanging("DateEnd");
                _DateEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateEnd");
                OnDateEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateEnd;
        partial void OnDateEndChanging(Nullable<global::System.DateTime> value);
        partial void OnDateEndChanged();

        #endregion
    
    }

    #endregion
    
}
